[package]
name = "sysnotify"
version = "0.1.0"
description = "Desktop notifications for systemd service failures"
license = "MIT"
authors = ["wvhulle"]
repository = "https://github.com/wvhulle/sysnotify"

[dependencies]

[dev-dependencies]